title: Blog 123
author: AC
email: your-email@domain.com
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  My blog test 123 description a b c

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  karmageddon # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
